domains:
  app_domain:
    aliases:
    - adom
    - d
    models:
      app_domain:
        class_name: AppDomain
        name: App Domain
      app_domain_model:
        class_name: AppDomainModel
        name: App Domain Model
    name: Domain
  app_interface:
    aliases:
    - i
    name: App Interface
  app_printer:
    class_name: AppPrinter
    name: App Printer
  app_project:
    aliases:
    - aproj
    - p
    models:
      app_project:
        class_name: AppProject
        name: App Project
    name: App Project
  cli:
    aliases: null
    name: cli
errors:
  APP_KEY_REQUIRED:
    error_code: '000000003'
    error_name: APP_KEY_REQUIRED
    message:
      en_US: App key is required
  APP_PROJECT_NOT_FOUND:
    error_code: '000010001'
    error_name: APP_PROJECT_NOT_FOUND
    message:
      en_US: App Project with key "{}" not found
  DOMAIN_ALREADY_EXISTS:
    error_code: '00002001'
    error_name: DOMAIN_ALREADY_EXISTS
    message:
      en_US: Domain with key "{}" already exists
  DOMAIN_IMPLEMENTATION_ALREADY_EXISTS:
    error_code: '000020006'
    error_name: DOMAIN_IMPLEMENTATION_ALREADY_EXISTS
    message:
      en_US: Domain implementation with key "{}" already exists
  DOMAIN_MODEL_ALREADY_EXISTS:
    error_code: '000020002'
    error_name: DOMAIN_MODEL_ALREADY_EXISTS
    message:
      en_US: Domain model with key "{}" already exists
  DOMAIN_MODEL_PROPERTY_ALREADY_EXISTS:
    error_code: '000020004'
    error_name: DOMAIN_MODEL_PROPERTY_ALREADY_EXISTS
    message:
      en_US: Domain model property with key "{}" already exists
  DOMAIN_NOT_FOUND:
    error_code: '000020005'
    error_name: DOMAIN_NOT_FOUND
    message:
      en_US: Domain with key "{}" not found
  DOMAIN_ROLE_ALREADY_EXISTS:
    error_code: '000020003'
    error_name: DOMAIN_ROLE_ALREADY_EXISTS
    message:
      en_US: Domain role with key "{}" already exists
  ENDPOINT_NOT_FOUND:
    error_code: '000000002'
    error_name: ENDPOINT_NOT_FOUND
    message:
      en_US: 'Unable to find the requested endpoint. Subdomain: {}, Module: {}'
    status_code: 404
  INVALID_REQUEST_DATA:
    error_code: '000000001'
    error_name: INVALID_REQUEST_DATA
    message:
      en_US: 'Invalid request contains the following errors: {}'
events: null
interfaces:
  cli:
    commands:
      domain:
        subcommands:
          add:
            arguments:
            - help: domain name
              name_or_flags:
              - name
            - help: domain key
              name_or_flags:
              - --key
              - -k
            - help: domain aliases
              name_or_flags:
              - --aliases
              - -a
              nargs: +
          add_implementation:
            arguments:
            - help: domain key
              name_or_flags:
              - --domain-key
              - -d
              required: true
            - help: domain implementation key
              name_or_flags:
              - --key
              - -k
            - help: domain implementation name
              name_or_flags:
              - name
          add_model:
            arguments:
            - help: domain model name
              name_or_flags:
              - name
            - help: domain key
              name_or_flags:
              - --domain-key
              - -d
              required: true
            - help: domain model key
              name_or_flags:
              - --key
              - -k
            - help: domain model class name
              name_or_flags:
              - --class-name
              - -c
          add_model_property:
            arguments:
            - help: domain model property name
              name_or_flags:
              - name
            - help: domain key
              name_or_flags:
              - -d
              - --domain-key
              required: true
            - help: domain model key
              name_or_flags:
              - -m
              - --model-key
              required: true
            - help: domain model property key
              name_or_flags:
              - -k
              - --key
            - choices:
              - str
              - int
              - float
              - bool
              - datetime
              - date
              - time
              - list
              - dict
              - model
              help: domain model property type
              name_or_flags:
              - -t
              - --type
            - action: store_true
              help: require value for domain model property
              name_or_flags:
              - --required
            - help: default domain model property value
              name_or_flags:
              - --default
            - help: available value choices for domain model property value
              name_or_flags:
              - --choices
              nargs: +
            - help: the domain model property key when serialized
              name_or_flags:
              - --serialized_name
            - help: the domain model property keys available to deserialize from
              name_or_flags:
              - --deserialize_from
              nargs: +
          add_role:
            arguments:
            - help: domain role name
              name_or_flags:
              - name
            - choices:
              - blacklist
              - whitelist
              help: domain role type
              name_or_flags:
              - --type
              - -t
              required: true
            - help: domain key
              name_or_flags:
              - --domain-key
              - -d
              required: true
      interface:
        subcommands:
          add:
            arguments:
            - choices:
              - cli
              - flask
              help: interface key
              name_or_flags:
              - -k
              - --key
              required: true
    parent_arguments:
    - help: app project key (not required when using default project)
      name_or_flags:
      - --app-key
    - choices:
      - dev
      - prod
      default: prod
      help: environment to run the command in
      name_or_flags:
      - --env
    - action: store_true
      help: run the command with verbose output
      name_or_flags:
      - --verbose
    - action: store_true
      help: force the command overwrite existing files when syncing
      name_or_flags:
      - --force
mappings:
  data: null
  header: null
  service: null
modules:
  app_project:
    features:
      new:
        functions:
        - data_mapping: new_app_project
          function_path: app_project.new_app_project
        header_mapping: app_project_headers
      set_default:
        functions:
        - data_mapping: set_default_app_project
          function_path: app_project.set_default_app_project
        header_mapping: app_project_headers
      sync:
        functions:
        - data_mapping: sync_app_project
          function_path: app_project.sync_app_project
        header_mapping: app_project_headers
  domain:
    features:
      add:
        functions:
        - data_mapping: add_domain
          function_path: domain.add_domain
      add_model:
        functions:
        - data_mapping: add_domain_model
          function_path: domain.add_model
      add_model_property:
        functions:
        - data_mapping: add_domain_model_property
          function_path: domain.add_domain_model_property
      add_role:
        functions:
        - data_mapping: add_domain_role
          function_path: domain.add_role
      update:
        functions:
        - data_mapping: update_domain
          function_path: domain.update_domain
  interface:
    features:
      add:
        functions:
        - data_mapping: add_interface
          function_path: interface.add_interface
