endpoints: 
  app_project:
    new:
      modules:
        - subdomain: app_project
          module: new_app_project
          data_mapping: new_app_project
errors: 
events: 
mappings:
  data: 
  header: 
  service: 
modules: 
services: 
