endpoints: 

errors: 
  INVALID_REQUEST_DATA:
    error_code: '000000001'
    error_name: 'INVALID_REQUEST_DATA'
    message: 
        en_US: 'Invalid request contains the following errors: {}'  
  ENDPOINT_NOT_FOUND:
    error_code: '000000002'
    error_name: 'ENDPOINT_NOT_FOUND'
    message: 
        en_US: 'Unable to find the requested endpoint. Subdomain: {}, Module: {}'
    status_code: 404

events: 

mappings:
  data: 
  header: 
  service: 

modules: 
  app_project:
    features:
      new:
        functions:
        - function_path: app_project.new_app_project
          data_mapping: new_app_project
      sync:
        functions:
        - function_path: app_project.sync_app_project
          data_mapping: sync_app_project
services: 
